export const environment = {
  production: true,
  api:"https://thechirpper.herokuapp.com",
  ws:"wss://thechirpper.herokuapp.com",
  loginroute:"/auth/login",
  registerroute:"/auth/register",
  sendemailverroute:"/auth/sendemailver",
  verifyemailverroute:"/auth/verifyemailver",
  verifytokenroute:"/endpoints/checktoken",
  initwsroute:"/endpoints/ws",
  profileroute:"/endpoints/profile",
  searchroute:"/endpoints/search",
  initcommentroute:"/endpoints/comment",
  postwithimageroute:"/endpoints/postwithimage",
  settingroute:"/endpoints/setting",
};
