export const environment = {
  production: true,
  api:"http://localhost:4040",
  ws:"ws://localhost:4040",
  loginroute:"/auth/login",
  registerroute:"/auth/register",
  sendemailverroute:"/auth/sendemailver",
  verifyemailverroute:"/auth/verifyemailver",
  verifytokenroute:"/endpoints/checktoken",
  initwsroute:"/endpoints/ws",
  profileroute:"/endpoints/profile",
  searchroute:"/endpoints/search",
  initcommentroute:"/endpoints/comment",
  postwithimageroute:"/endpoints/postwithimage",
};
